services:
  - type: web
    name: b3-simulator
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
